common file implementation across all modules, with colorized common output

diff --git a/ce b/ce
--- a/ce
+++ b/ce
@@ -47,8 +47,6 @@ declare -ir FALSE=0
 
 declare -r PROGNAME="$(basename ${0})"
 declare -r VERSION=0.0.1
-declare -r SUBJECT=""
-declare -r KEYS=""
 declare -ri MIN_ARG_COUNT=1
 declare -r SYNTAX=$(cat <<EOF
     Script: ${PROGNAME}
@@ -66,11 +64,11 @@ declare -r SYNTAX=$(cat <<EOF
     Examples:
       ${PROGNAME} --last=30
       ${PROGNAME} --last=365 --monthly
-
 EOF
 )
 # files & directories
 declare -r SCRIPT_DIR="$( dirname ${0} )"
+declare -r COMMON_FILE="${SCRIPT_DIR}/aws-common.sh"
 
 # actions
 declare -i LAST=${FALSE}
@@ -81,38 +79,12 @@ declare OS_NAME=$( uname -s )
 declare GRANULARITY='DAILY'
 
 # ---------------------------------------
-# COMMON FUNCTIONS
-# ---------------------------------------
-usage() {
-  echo "${SYNTAX}"
-}
-
-error() {
-  printf "\n%s\n" "Error: ${1}"
-}
-
-die() {
-  error "${1}"
-  usage
-  printf "\n\n"
-  exit "${2:-1}"
-}
-
-show_version() {
-  printf "\n\n%s  %s\n\n\n" "${PROGNAME}" "${VERSION}"
-  exit 0
-}
-
-show_help() {
-  printf "\n\n"
-  usage
-  printf "\n\n"
-  exit 0
-}
-
-# ---------------------------------------
 # MAIN ROUTINES
 # ---------------------------------------
+# do not have 'die()' routine yet - in common file
+source "${COMMON_FILE}" || \
+  { echo "Could not load common file: ${COMMON_FILE}"; exit 1; }
+
 
 __days_back() {
   local days=${1:-${DAYS}};
diff --git a/img b/img
--- a/img
+++ b/img
@@ -47,11 +47,8 @@ declare -ir FALSE=0
 
 declare -r PROGNAME="$(basename ${0})"
 declare -r VERSION=0.0.1
-declare -r SUBJECT=""
-declare -r KEYS=""
 declare -ri MIN_ARG_COUNT=1
 declare -r SYNTAX=$(cat <<EOF
-
     Script: ${PROGNAME}
     Purpose: Manage AWS Images
     Usage: ${PROGNAME} [-h|--help] [-v|--version]
@@ -73,6 +70,7 @@ EOF
 )
 # files & directories
 declare -r SCRIPT_DIR="$( dirname ${0} )"
+declare -r COMMON_FILE="${SCRIPT_DIR}/aws-common.sh"
 declare -r CONFIG_FILE="${SCRIPT_DIR}/ec2.conf.sh"
 declare -r EC2_LIB_FILE="${SCRIPT_DIR}/ec2.sh"
 
@@ -91,43 +89,17 @@ declare IMAGE_NAME=''
 declare INSTANCE_NAME=''
 
 # ---------------------------------------
-# COMMON FUNCTIONS
-# ---------------------------------------
-usage() {
-  echo "${SYNTAX}"
-}
-
-error() {
-  printf "\n%s\n" "Error: ${1}"
-}
-
-die() {
-  error "${1}"
-  usage
-  printf "\n\n"
-  exit "${2:-1}"
-}
-
-show_version() {
-  printf "\n\n%s  %s\n\n\n" "${PROGNAME}" "${VERSION}"
-  exit 0
-}
-
-show_help() {
-  printf "\n\n"
-  usage
-  printf "\n\n"
-  exit 0
-}
-
-# ---------------------------------------
 # MAIN ROUTINES
 # ---------------------------------------
+# do not have 'die()' routine yet - in common file
+source "${COMMON_FILE}" || \
+  { echo "Could not load common file: ${COMMON_FILE}"; exit 1; }
+
 source "${CONFIG_FILE}" \
-  || die "Unable to load config file: ${CONFIG_FILE}" 1
+  || die "Unable to load config file: ${CONFIG_FILE}" 2
 
 source "${EC2_LIB_FILE}" \
-  || die "Unable to load ec2 lib file: ${EC2_LIB_FILE}" 2
+  || die "Unable to load ec2 lib file: ${EC2_LIB_FILE}" 3
 
 __get_image_id() {
   local os=${1:-${OS}}
diff --git a/sns b/sns
--- a/sns
+++ b/sns
@@ -49,7 +49,6 @@ declare -r PROGNAME="$(basename ${0})"
 declare -r VERSION=0.0.1
 declare -ri MIN_ARG_COUNT=1
 declare -r SYNTAX=$(cat <<EOF
-
     Script: ${PROGNAME}
     Purpose: Wraps AWS SNS (Simple Notification Service)
     Usage: ${PROGNAME} [options]
@@ -82,8 +81,8 @@ declare -r SYNTAX=$(cat <<EOF
         ${PROGNAME} --send="My message" --topic=My-Topic --subject="My Subject" --timestamp
         ${PROGNAME} --list-top
         ${PROGNAME} --list-sub
+        ${PROGNAME} --unsubscribe=My-Topic --email=name@domain.com
         ${PROGNAME} --delete=My-Topic
-
 EOF
 )
 # files & directories
@@ -107,15 +106,14 @@ declare TOPIC_NAME=''
 declare TOPIC_ARN=''
 declare TOPIC_MESSAGE=''
 declare TOPIC_SUBJECT=''
-
-
+declare EMAIL=''
 
 # ---------------------------------------
 # MAIN ROUTINES
 # ---------------------------------------
-# do not have 'die()' routine - in common file
+# do not have 'die()' routine yet - in common file
 source "${COMMON_FILE}" || \
-  { echo "Could not load common file: ${COMMON_FILE}"; exit 2; }
+  { echo "Could not load common file: ${COMMON_FILE}"; exit 1; }
 
 __build_topic_arn() {
   [[ -z "${TOPIC_NAME}" ]]
@@ -148,9 +146,41 @@ __subscribe() {
 
 __unsubscribe() {
   # TODO: Unsubscribe, fetch subscription id(s) - build call
-  local url='https://sns.us-west-2.amazonaws.com/unsubscribe.html?SubscriptionArn=arn:aws:sns:us-west-2:734741078887:S3-Glacier-Backup:7b399f3f-8ac4-4fb7-82a3-4447274632e4&Endpoint=xybersolve@gmail.com'
-  local url2="https://sns.${REGION}.amazonaws.com/unsubscribe.html?SubscriptionArn=arn:${TOPIC_ARN}:${SUBSCRIPTION_ID}&Endpoint=${ADMIN_EMAIL}"
-  :
+  #local url='https://sns.us-west-2.amazonaws.com/unsubscribe.html?SubscriptionArn=arn:aws:sns:us-west-2:734741078887:S3-Glacier-Backup:7b399f3f-8ac4-4fb7-82a3-4447274632e4&Endpoint=xybersolve@gmail.com'
+  #local url2="https://sns.${REGION}.amazonaws.com/unsubscribe.html?SubscriptionArn=arn:${TOPIC_ARN}:${SUBSCRIPTION_ID}&Endpoint=${ADMIN_EMAIL}"
+  local sub_arn=''
+  local -a sub_arms=()
+
+  if [[ -n ${ADMIN_EMAIL} ]]; then
+    # if email is supplied, should return one item, if any
+    sub_arn=$( aws sns list-subscriptions --output text \
+      | grep "${TOPIC_NAME}" \
+      | grep "${EMAIL}" \
+      | awk '{print $5}' )
+
+    [[ -z "${sub_arn}" ]] && die "No subscription for for that topic and email" 6
+
+    echo "${sub_arn}"
+    #aws sns unsubscribe --subscription-arn "${sub_arn}"
+
+  else
+    # given a topic and no email, there could be multiple subscriptions
+    sub_arns=( $(aws sns list-subscriptions --output text \
+      | grep "${TOPIC_NAME}" \
+      | awk '{print $5}' ) )
+
+    (( ${#sub_arns[@]} == 0 )) && die "No subscription for for that topic" 7
+
+    for arn in "${sub_arns[@]}"; do
+      echo ${arn}
+      #aws sns unsubscribe --subscription-arn "${sub_arn}"
+    done
+  fi
+
+  # subscription arns
+  #aws sns list-subscriptions --output text | grep My-New-Topic | awk '{print $5}'
+  # email arns
+  #aws sns list-subscriptions --output text | grep My-New-Topic | awk '{print $2}'
 }
 
 __setup_topic() {
@@ -241,11 +271,14 @@ __get_opts() {
       --subject*)
         [[ ${arg} =~ '=' ]] && TOPIC_SUBJECT="${arg#*=}"
         ;;
-      --topic*) # --option=argument
+      --topic*)
         [[ ${arg} =~ '=' ]] && TOPIC_NAME="${arg#*=}"
         ;;
-      --email*) # --option=argument
-        [[ ${arg} =~ '=' ]] && ADMIN_EMAIL="${arg#*=}"
+      --email*)
+        if [[ ${arg} =~ '=' ]]; then
+          ADMIN_EMAIL="${arg#*=}"
+          EMAIL="${ADMIN_EMAIL}"
+        fi
         ;;
       *) die "Unknown option: ${arg}" ;;
    esac
